createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: project
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .key
          title: .name
          blueprint: '"jiraProject"'
          properties:
            url: (.self | split("/") | .[:3] | join("/")) + "/projects/" + .key
            totalIssues: .insight.totalIssueCount

  - kind: user
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .accountId
          title: .displayName
          blueprint: '"jiraUser"'
          properties:
            emailAddress: .emailAddress
            displayName: .displayName
            active: .active
            accountType: .accountType
            timeZone: .timeZone
            locale: .locale
            avatarUrl: .avatarUrls["48x48"]

  - kind: issue
    selector:
      query: "true"
      jql: "(statusCategory != Done) OR (created >= -1w) OR (updated >= -1w)"
    port:
      entity:
        mappings:
          identifier: .key
          title: .fields.summary
          blueprint: '"jiraIssue"'
          properties:
            url: (.self | split("/") | .[:3] | join("/")) + "/browse/" + .key
            status: .fields.status.name
            issueType: .fields.issuetype.name
            components: .fields.components
            creator: .fields.creator.emailAddress // ""
            priority: .fields.priority.name
            labels: .fields.labels
            created: .fields.created
            updated: .fields.updated
            resolutionDate: .fields.resolutiondate // ""
          relations:
            project: .fields.project.key
            parentIssue: .fields.parent.key // ""
            subtasks: .fields.subtasks | map(.key)
            assignee: .fields.assignee.accountId // ""
            reporter: .fields.reporter.accountId
