createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: services
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"pagerdutyService"'
          properties:
            status: .status
            url: .html_url
            oncall: .__oncall_user | sort_by(.escalation_level) | .[0].user.email
            secondaryOncall: .__oncall_user | sort_by(.escalation_level) | .[1].user.email
            escalationLevels: .__oncall_user | map(.escalation_level) | unique | length
            meanSecondsToResolve: .__analytics.mean_seconds_to_resolve
            meanSecondsToFirstAck: .__analytics.mean_seconds_to_first_ack
            meanSecondsToEngage: .__analytics.mean_seconds_to_engage
  - kind: incidents
    selector:
      query: 'true'
      apiQueryParams:
        include:
          - assignees
          - first_trigger_log_entries
        statuses:
          - triggered
          - acknowledged
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .title
          blueprint: '"pagerdutyIncident"'
          properties:
            status: .status
            url: .html_url
            urgency: .urgency
            assignees: .assignments | map(.assignee.email)
            escalation_policy: .escalation_policy.summary
            created_at: .created_at
            updated_at: .updated_at
            priority: if .priority != null then .priority.summary else null end
            description: .description
            triggered_by: .first_trigger_log_entry.agent.summary
          relations:
            pagerdutyService: .service.id
  - kind: incidents
    selector:
      query: 'true'
      apiQueryParams:
        include:
          - assignees
          - first_trigger_log_entries
        statuses:
          - resolved
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .title
          blueprint: '"pagerdutyIncident"'
          properties:
            status: .status
            url: .html_url
            urgency: .urgency
            escalation_policy: .escalation_policy.summary
            created_at: .created_at
            updated_at: .updated_at
            priority: if .priority != null then .priority.summary else null end
            description: .description
            triggered_by: .first_trigger_log_entry.agent.summary
          relations:
            pagerdutyService: .service.id
  - kind: schedules
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"pagerdutySchedule"'
          properties:
            url: .html_url
            timezone: .time_zone
            description: .description
            users: '[.users[] | select(has("__email")) | .__email]'
  - kind: oncalls
    selector:
      query: 'true'
      apiQueryParams:
        include:
          - users
    port:
      entity:
        mappings:
          identifier: .user.id + "-" + .schedule.id + "-" + .start
          title: .user.name
          blueprint: '"pagerdutyOncall"'
          properties:
            user: .user.email
            startDate: .start
            endDate: .end
            url: .schedule.html_url
          relations:
            pagerdutySchedule: .schedule.id
            pagerdutyEscalationPolicy: .escalation_policy.id
  - kind: escalation_policies
    selector:
      query: 'true'
      attachOncallUsers: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"pagerdutyEscalationPolicy"'
          properties:
            url: .html_url
            description: .summary
            primaryOncall: .__oncall_users | sort_by(.escalation_level) | .[0].user.email
            escalationRules: .escalation_rules
  - kind: users
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"pagerdutyUser"'
          properties:
            url: .html_url
            time_zone: .time_zone
            email: .email
            description: .description
            role: .role
            job_title: .job_title
            teams: .teams
            contact_methods: .contact_methods
