resources:
  - kind: subscription
    selector:
      query: 'true'
      apiVersion: '2022-09-01'
    port:
      entity:
        mappings:
          identifier: .id
          title: .display_name
          blueprint: '"azureSubscription"'
          properties: {}
  - kind: Microsoft.Resources/resourceGroups
    selector:
      query: 'true'
      apiVersion: '2022-09-01'
    port:
      entity:
        mappings:
          identifier: >-
            .id | split("/") | .[3] |= ascii_downcase |.[4] |= ascii_downcase |
            join("/")
          title: .name
          blueprint: '"azureResourceGroup"'
          properties:
            location: .location
            provisioningState: .properties.provisioningState + .properties.provisioning_state
            tags: .tags
          relations:
            subscription: >-
              .id | split("/") | .[1] |= ascii_downcase |.[2] |= ascii_downcase
              | .[:3] |join("/")
  - kind: Microsoft.App/containerApps
    selector:
      query: 'true'
      apiVersion: '2022-03-01'
    port:
      entity:
        mappings:
          identifier: >-
            .id | split("/") | .[3] |= ascii_downcase |.[4] |= ascii_downcase |
            join("/")
          title: .name
          blueprint: '"azureCloudResource"'
          properties:
            location: .location
            type: .type
            tags: .tags
          relations:
            resource_group: >-
              .id | split("/") | .[3] |= ascii_downcase |.[4] |= ascii_downcase
              | .[:5] |join("/")
  - kind: Microsoft.Storage/storageAccounts
    selector:
      query: 'true'
      apiVersion: '2023-01-01'
    port:
      entity:
        mappings:
          identifier: >-
            .id | split("/") | .[3] |= ascii_downcase |.[4] |= ascii_downcase |
            join("/")
          title: .name
          blueprint: '"azureCloudResource"'
          properties:
            location: .location
            type: .type
            tags: .tags
          relations:
            resource_group: >-
              .id | split("/") | .[3] |= ascii_downcase |.[4] |= ascii_downcase
              | .[:5] |join("/")
  - kind: Microsoft.Compute/virtualMachines
    selector:
      query: 'true'
      apiVersion: '2023-03-01'
    port:
      entity:
        mappings:
          identifier: >-
            .id | split("/") | .[3] |= ascii_downcase |.[4] |= ascii_downcase |
            join("/")
          title: .name
          blueprint: '"azureCloudResource"'
          properties:
            location: .location
            type: .type
            tags: .tags
          relations:
            resource_group: >-
              .id | split("/") | .[3] |= ascii_downcase |.[4] |= ascii_downcase
              | .[:5] |join("/")
  - kind: Microsoft.ContainerService/managedClusters
    selector:
      query: 'true'
      apiVersion: '2023-05-01'
    port:
      entity:
        mappings:
          identifier: >-
            .id | split("/") | .[3] |= ascii_downcase |.[4] |= ascii_downcase |
            join("/")
          title: .name
          blueprint: '"azureCloudResource"'
          properties:
            location: .location
            type: .type
            tags: .tags
          relations:
            resource_group: >-
              .id | split("/") | .[3] |= ascii_downcase |.[4] |= ascii_downcase
              | .[:5] |join("/")
  - kind: Microsoft.Network/loadBalancers
    selector:
      query: 'true'
      apiVersion: '2023-02-01'
    port:
      entity:
        mappings:
          identifier: >-
            .id | split("/") | .[3] |= ascii_downcase |.[4] |= ascii_downcase |
            join("/")
          title: .name
          blueprint: '"azureCloudResource"'
          properties:
            location: .location
            type: .type
            tags: .tags
          relations:
            resource_group: >-
              .id | split("/") | .[3] |= ascii_downcase |.[4] |= ascii_downcase
              | .[:5] |join("/")
