createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: workspace
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .id
          title: .attributes.name
          blueprint: '"terrafomCloudWorkspace"'
          properties:
            organization: .relationships.organization.data.id
            createdAt: .attributes."created-at"
            updatedAt: .attributes."updated-at"
            terraformVersion: .attributes."terraform-version"
            locked: .attributes.locked
            executionMode: .attributes."execution-mode"
            resourceCount: .attributes."resource-count"
            latestChangeAt: .attributes."latest-change-at"
          relations:
            currentStateVersion: .relationships."current-state-version".data.id
  - kind: run
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .id
          title: .attributes.message
          blueprint: '"terraformCloudRun"'
          properties:
            createdAt: .attributes."created-at"
            status: .attributes.status
            hasChanges: .attributes."has-changes"
            isDestroy: .attributes."is-destroy"
            message: .attributes.message
            terraformVersion: .attributes."terraform-version"
            appliedAt: .attributes."status-timestamps"."applied-at"
            plannedAt: .attributes."status-timestamps"."planned-at"
            source: .attributes.source
          relations:
            terraformCloudWorkspace: .relationships.workspace.data.id
  - kind: state-version
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .id
          title: .id
          blueprint: '"terraformCloudStateVersion"'
          properties:
            createdAt: .attributes."created-at"
            serial: .attributes.serial
            status: .attributes.status
            size: .attributes.size
            isResourcesProcessed: .attributes."resources-processed"
            hostedStateDownloadUrl: .attributes."hosted-state-download-url"
            hostedJsonDownloadUrl: .attributes."hosted-json-state-download-url"
            vcsCommitUrl: .attributes."vcs-commit-url"
            outputData: .__output
