createMissingRelatedEntities: true
resources:
  - kind: newRelicService
    selector:
      query: 'true'
      newRelicTypes:
        - SERVICE
        - APPLICATION
      calculateOpenIssueCount: true
      entityQueryFilter: "type in ('SERVICE','APPLICATION')"
      entityExtraPropertiesQuery: |
        ... on ApmApplicationEntityOutline {
          guid
          name
          alertSeverity
          applicationId
          apmBrowserSummary {
            ajaxRequestThroughput
            ajaxResponseTimeAverage
            jsErrorRate
            pageLoadThroughput
            pageLoadTimeAverage
          }
          apmSummary {
            apdexScore
            errorRate
            hostCount
            instanceCount
            nonWebResponseTimeAverage
            nonWebThroughput
            responseTimeAverage
            throughput
            webResponseTimeAverage
            webThroughput
          }
        }
    port:
      entity:
        mappings:
          blueprint: '"newRelicService"'
          identifier: .guid
          title: .name
          properties:
            has_apm: 'if .domain | contains("APM") then "true" else "false" end'
            link: .permalink
            open_issues_count: .open_issues_count
            reporting: .reporting
            tags: .tags
            domain: .domain
            type: .type
            throughput: .apmSummary.throughput
            error_rate: .apmSummary.errorRate
            response_time_avg: .apmSummary.responseTimeAverage
            instance_count: .apmSummary.instanceCount
  - kind: newRelicAlert
    selector:
      query: 'true'
      newRelicTypes: ['ISSUE']
    port:
      entity:
        mappings:
          blueprint: '"newRelicAlert"'
          identifier: .issueId
          title: .title[0]
          properties:
            priority: .priority
            state: .state
            sources: .sources
            conditionName: .conditionName
            alertPolicyNames: .policyName
            activatedAt: .activatedAt
          relations:
            newRelicService: ".__APPLICATION.entity_guids + .__SERVICE.entity_guids"
  - kind: newRelicServiceLevel
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          blueprint: '"newRelicServiceLevel"'
          identifier: .serviceLevel.indicators[0].id
          title: .serviceLevel.indicators[0].name
          properties:
            description: .serviceLevel.indicators[0].description
            targetThreshold: .serviceLevel.indicators[0].objectives[0].target
            createdAt: if .serviceLevel.indicators[0].createdAt != null then (.serviceLevel.indicators[0].createdAt | tonumber / 1000 | todate) else null end
            updatedAt: .serviceLevel.indicators[0].updatedAt
            createdBy: .serviceLevel.indicators[0].createdBy.email
            sli: .__SLI.SLI
            tags: .tags
          relations:
            newRelicService: .serviceLevel.indicators[0].guid
  - kind: entity
    selector:
      query: 'true'
      entityQueryFilter:
        type IN (
          'AWSEC2INSTANCE',
          'AWSS3BUCKET',
          'AWSRDSDBINSTANCE',
          'AWSLAMBDAFUNCTION',
          'AWSELBLOADBALANCER',
          'AZUREVIRTUALMACHINE',
          'AZURESQLDATABASE',
          'GCPCOMPUTEINSTANCE',
          'GCPSTORAGEBUCKET',
          'GCPSQLDATABASEINSTANCE'
        )
    port:
      entity:
        mappings:
          identifier: .guid
          title: .name
          blueprint: '"newRelicEntityCloudResource"'
          properties:
            accountId: .accountId
            domain: .domain
            type: .entityType
            infrastructureIntegrationType: .type
            reporting: .reporting
            link: .permalink
            tags: .tags
