createMissingRelatedEntities: true
resources:
  - kind: newRelicService
    selector:
      query: 'true'
      newRelicTypes:
        - SERVICE
        - APPLICATION
      calculateOpenIssueCount: true
      entityQueryFilter: "type in ('SERVICE','APPLICATION')"
      entityExtraPropertiesQuery: |
        ... on ApmApplicationEntityOutline {
          guid
          name
          alertSeverity
          applicationId
          apmBrowserSummary {
            ajaxRequestThroughput
            ajaxResponseTimeAverage
            jsErrorRate
            pageLoadThroughput
            pageLoadTimeAverage
          }
          apmSummary {
            apdexScore
            errorRate
            hostCount
            instanceCount
            nonWebResponseTimeAverage
            nonWebThroughput
            responseTimeAverage
            throughput
            webResponseTimeAverage
            webThroughput
          }
        }
    port:
      entity:
        mappings:
          blueprint: '"newRelicService"'
          identifier: .guid
          title: .name
          properties:
            has_apm: 'if .domain | contains("APM") then "true" else "false" end'
            link: .permalink
            open_issues_count: .open_issues_count
            reporting: .reporting
            tags: .tags
            domain: .domain
            type: .type
            throughput: .apmSummary.throughput
            error_rate: .apmSummary.errorRate
            response_time_avg: .apmSummary.responseTimeAverage
            instance_count: .apmSummary.instanceCount
  - kind: newRelicAlert
    selector:
      query: 'true'
      newRelicTypes: ['ISSUE']
    port:
      entity:
        mappings:
          blueprint: '"newRelicAlert"'
          identifier: .issueId
          title: .title[0]
          properties:
            priority: .priority
            state: .state
            sources: .sources
            conditionName: .conditionName
            alertPolicyNames: .policyName
            activatedAt: .activatedAt
          relations:
            newRelicService: ".__APPLICATION.entity_guids + .__SERVICE.entity_guids"
