resources:
  - kind: organization
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .attributes.name
          blueprint: '"snykOrganization"'
          properties:
            slug: .attributes.slug
            url: ("https://app.snyk.io/org/" + .attributes.slug | tostring)
  - kind: project
    selector:
      query: 'true'
      attachIssuesToProject: 'false'
    port:
      entity:
        mappings:
          identifier: .id
          title: .attributes.name
          blueprint: '"snykProject"'
          properties:
            url: ("https://app.snyk.io/org/" + .relationships.organization.data.id + "/project/" + .id | tostring)
            businessCriticality: .attributes.business_criticality
            environment: .attributes.environment
            lifeCycle: .attributes.lifecycle
            highOpenVulnerabilities: .meta.latest_issue_counts.high
            mediumOpenVulnerabilities: .meta.latest_issue_counts.medium
            lowOpenVulnerabilities: .meta.latest_issue_counts.low
            criticalOpenVulnerabilities: .meta.latest_issue_counts.critical
            tags: .attributes.tags
            targetOrigin: .attributes.origin
          relations:
            snyk_target: '.relationships.target.data.id'
  - kind: target
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .attributes.display_name
          blueprint: '"snykTarget"'
          properties:
            origin: .relationships.integration.data.attributes.integration_type
          relations:
            snyk_organization: '.relationships.organization.data.id'
  - kind: vulnerability
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: .attributes.title
          blueprint: '"snykVulnerability"'
          properties:
            score: .attributes.risk.score.value
            packageNames: '[.attributes.coordinates[].representations[].dependency?.package_name | select(. != null)]'
            packageVersions: '[.attributes.coordinates[].representations[].dependency?.package_version | select(. != null)]'
            severity: .attributes.effective_severity_level
            url: ("https://app.snyk.io/org/" + .attributes.key | tostring)
            publicationTime: .attributes.created_at
            status: .attributes.status
            type: .attributes.type
          relations:
            project: .relationships.scan_item.data.id
